version: "3.7"
services:
  influxdb:
    image: influxdb:2.7
    ports:
      - 8086:8086
  golang:
    image: tsbs:0.1
  questdb:
    image: questdb/questdb
    ports:
      - 8812:8812
      - 9009:9009
      - 9000:9000