version: "3.7"
services:
  influxdb:
    build: influx-docker
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=gabriel
      - DOCKER_INFLUXDB_INIT_PASSWORD=estaesunamalacontrasena
      - DOCKER_INFLUXDB_INIT_ORG=ulb
      - DOCKER_INFLUXDB_INIT_BUCKET=benchmark
    image: influxdb:2.7
    ports:
      - 8086:8086
  golang:
    container_name: golang
    build: tsbs-master
    image: tsbs:0.1
  postgres:
    image: postgres:latest
    environment:
     - POSTGRES_PASSWORD=estaesunamalacontrasena
     - NO_TS_TUNE=true
     - POSTGRES_DB=benchmark
     - POSTGRES_USER=postgres
    ports:
      - 5432:5432
  # timescaledb:
  #   image: timescale/timescaledb:latest-pg16
  #   environment:
  #    - POSTGRES_PASSWORD=estaesunamalacontrasena
  #    - POSTGRES_DB=benchmark
  #    - POSTGRES_USER=postgres
  #   ports:
  #     - 5433:5432 
  questdb:
    image: questdb/questdb
    ports:
      - 8812:8812
      - 9009:9009
      - 9000:9000
