version: "3.7"
services:
  influxdb:
    build: influx-docker
    container_name: benchmark-influxdb-1
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=gabriel
      - DOCKER_INFLUXDB_INIT_PASSWORD=estaesunamalacontrasena
      - DOCKER_INFLUXDB_INIT_ORG=ulb
      - DOCKER_INFLUXDB_INIT_BUCKET=benchmark
    image: influxdb:2.7
    ports:
      - 8086:8086
  golang:
    container_name: golang
    build: tsbs-master
    image: tsbs:0.1
    volumes:
     - ./data/:/data/
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: benchmark-timescaledb-1
    environment:
     - POSTGRES_PASSWORD=estaesunamalacontrasena
     - POSTGRES_DB=postgres
     - POSTGRES_USER=postgres
    ports:
      - 5432:5432 
  questdb:
    container_name: benchmark-questdb-1
    image: questdb/questdb
    ports:
      - 8812:8812
      - 9009:9009
      - 9000:9000
